import { Category, Dish } from "./types";

export const MENU_DATA: Dish[] = [
  {
    id: "1",
    number: "10",
    name: "Döner Kebab",
    category: Category.MEAT,
    price: 7.50,
    description: "Frisch gegrilltes Scheibenfleisch, hausgemachte Soßen, knuspriges Brot.",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&q=80&w=800",
    isBestseller: true,
  },
  {
    id: "2",
    number: "11",
    name: "Yufka Döner",
    category: Category.MEAT,
    price: 7.90,
    description: "Dönerfleisch im dünnen Fladenbrot gerollt mit frischem Salat.",
  },
  {
    id: "3",
    number: "30",
    name: "Falafel Wrap",
    category: Category.VEGAN,
    price: 6.50,
    description: "Hausgemachte Falafel, Hummus, frischer Salat und vegane Soße.",
  },
  {
    id: "4",
    number: "40",
    name: "Vegetarisches Pide",
    category: Category.VEGETARIAN,
    price: 5.90,
    description: "Frisch gebackenes Schiffchen mit Schafskäse und Spinat.",
  },
  {
    id: "5",
    number: "20",
    name: "Hamburger XL",
    category: Category.MEAT,
    price: 6.90,
    description: "Saftiges Rindfleisch, Spezialsoße, Salat und Tomaten.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800",
    isBestseller: true,
  },
  {
    id: "6",
    number: "50",
    name: "Currywurst",
    category: Category.MEAT,
    price: 4.50,
    description: "Klassische Currywurst mit pikanter Soße und Brot.",
    image: "https://images.unsplash.com/photo-1599599810694-b5b37304c041?auto=format&fit=crop&q=80&w=800",
    isBestseller: true,
  },
  {
    id: "7",
    number: "60",
    name: "Schnitzel Wiener Art",
    category: Category.MEAT,
    price: 9.50,
    description: "Zartes Schweineschnitzel, paniert und goldbraun gebraten.",
  },
  {
    id: "8",
    number: "70",
    name: "Chicken Nuggets (6 Stk.)",
    category: Category.MEAT,
    price: 4.90,
    description: "Knusprige Hähnchen-Nuggets mit Dip nach Wahl.",
  },
  {
    id: "9",
    number: "31",
    name: "Falafel Teller",
    category: Category.VEGETARIAN,
    price: 8.50,
    description: "Falafel-Bällchen mit Reis, Salat und Joghurt-Soße.",
  },
  {
    id: "10",
    number: "100",
    name: "Ayran",
    category: Category.DRINK,
    price: 2.50,
    description: "Erfrischendes Joghurtgetränk.",
  },
  {
    id: "11",
    number: "101",
    name: "Cola",
    category: Category.DRINK,
    price: 3.00,
    description: "0,33l Dose.",
  },
  {
    id: "12",
    number: "102",
    name: "Fanta",
    category: Category.DRINK,
    price: 3.00,
    description: "0,33l Dose.",
  },
  {
    id: "13",
    number: "103",
    name: "Naturradler",
    category: Category.DRINK,
    price: 3.50,
    description: "0,5l Flasche.",
  }
];
